/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[created_at]
      ,[updated_at]
      ,[number]
      ,[odometer]
      ,[odometer_out]
      ,[state]
      ,[customer_id]
      ,[technician_id]
      ,[advisor_id]
      ,[vehicle_id]
      ,[detail]
      ,[preferred_contact_type]
      ,[part_discount_cents]
      ,[labor_discount_cents]
      ,[shop_id]
      ,[status_id]
      ,[taxable]
      ,[customer_source]
      ,[supply_fee_cents]
      ,[part_discount_percentage]
      ,[labor_discount_percentage]
      ,[started_at]
      ,[closed_at]
      ,[picked_up_at]
      ,[due_in_at]
      ,[due_out_at]
      ,[part_tax_rate]
      ,[labor_tax_rate]
      ,[hazmat_tax_rate]
      ,[sublet_tax_rate]
      ,[label]
  FROM [Shopware].[dbo].[RO_Repair_Orders]